
    const data={
    products: [
      {
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 60,
        countInstock: 10,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Adidas fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 120,countInstock: 20,
        brand: ' Nike',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 60,countInstock: 0,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p4.jpg',
        price: 60,countInstock: 15,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p5.jpg',
        price: 60,countInstock: 30,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/p6.jpg',
        price: 60,countInstock: 5,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      
    ],
}
export default data;